### ISSUE TITLE
Why create an independent project instead of contributing to NixOS?

### ISSUE THREAD

**Issue by davidak** [andir/nixos.cloud#17]
https://github.com/NixOS/nixos-homepage/issues/447
https://github.com/NixOS/nixos-homepage/issues/266

**Comment by andir** [comment]
I wanted to get it done because I had a need *now* and didn't want to jump through bikeshedding and dealing with flakes to get this done.

In the past it had been hard to get any kind of new isos added to the release jobs due to concerns regarding their size. I didn't want to start that discussion again.
